name: updateBydszb
on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: 0 */1 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 检出
        uses: actions/checkout@v4
      - name: 创建Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 更新
        run: node fetchURLByzbpro.js
      - name: 生成mivgo文件
        run: node mivgo.js
      - name: 合并
        run: |
          OWNER=${{ github.repository_owner }}
          mkdir -p HD/output
          curl -s https://raw.githubusercontent.com/${OWNER}/HD/master/output/result.m3u -o HD/output/result.m3u
          node mergeChannels.js
      - name: 推送
        run: |
          if ! git diff --quiet --exit-code || [ -n "$(git status --porcelain)" ]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add .
            git commit -m "Update by GitHub Actions"
            git push
          fi
      - name: cnb
        run: |
          OWNER=${{ github.repository_owner }}
          git clone https://${{ secrets.CNB_PAT }}@github.com/${OWNER}/cnb.git
          cp mivgo.gz cnb/
          cp mivgo.m3u cnb/
          cd cnb
          if ! git diff --quiet --exit-code || [ -n "$(git status --porcelain)" ]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add mivgo.gz mivgo.m3u result.m3u
            git commit -m "Update mivgo files by GitHub Actions"
            git push origin main
          fi
